name: janmarten_name

services:
  clean:
    init: true
    tty: true
    environment:
      - "APP_ENV=${APP_ENV:-dev}"
      - "APP_SECRET=${APP_SECRET:-}"
    volumes:
      - .:/app
    profiles:
      - clean
    build:
      target: dev
      context: .
      args:
        PHP_VERSION: 8.3
        PHP_EXTENSIONS: '@composer intl'
        NODE_VERSION: 16
    command:
      - make
      - clean

  build:
    extends:
      service: clean
    profiles:
      - build
    command:
      - make
      - build

  local:
    extends:
      service: build
    depends_on:
      build:
        condition: service_completed_successfully
    command:
      - make
      - public/index.html

  app:
    extends:
      service: clean
    depends_on:
      local:
        condition: service_completed_successfully
    ports:
      - '8080:8080'
    command:
      - npm
      - run
      - dev-server
