name: janmarten_name

services:
  # Base service and IDE interpreter.
  clean:
    init: true
    tty: true
    environment:
      - "APP_ENV=${APP_ENV:-dev}"
      - "APP_SECRET=${APP_SECRET:-}"
    volumes:
      - .:/app
    profiles:
      - clean
    build:
      target: dev
      context: .
      args:
        PHP_VERSION: 8.3
        PHP_EXTENSIONS: '@composer intl'
        NODE_VERSION: 16
    command:
      - make
      - clean

  # Composer interpreter.
  composer:
    extends:
      service: clean
    build:
      target: composer
    profiles:
      - composer
    command:
      - composer

  # Dockerized build.
  build:
    extends:
      service: clean
    profiles:
      - build
      - app
    command:
      - make
      - build

  # Local development front-end.
  front-end:
    profiles:
      - app
    extends:
      service: clean
    depends_on:
      build:
        condition: service_completed_successfully
    ports:
      - '8080:8080'
    command:
      - npm
      - run
      - dev-server

  # Local development back-end.
  back-end:
    profiles:
      - app
    extends:
      service: clean
    build:
      target: symfony
    depends_on:
      build:
        condition: service_completed_successfully
    command:
      - symfony
      - local:server:start
      - --allow-http
      - --no-tls
      - --allow-all-ip
      - --allow-cors
    ports:
      - '8000:8000'