name: janmarten_name

services:
  clean:
    init: true
    tty: true
    volumes:
      - .:/app
    profiles:
      - clean
    build:
      target: dev
      context: .
      args:
        PHP_VERSION: 8.3
        PHP_EXTENSIONS: '@composer intl'
        NODE_VERSION: 16
    command:
      - make
      - clean

  build:
    extends:
      service: clean
    profiles:
      - build
    environment:
      - "APP_ENV=${APP_ENV:-dev}"
      - "APP_SECRET=${APP_SECRET:-change}"
    command:
      - make
      - build

  install:
    extends:
      service: clean
    profiles:
      - install
    command:
      - make
      - install
      - public/index.html

  app:
    extends:
      service: clean
    depends_on:
      install:
        condition: service_completed_successfully
    ports:
      - '8080:8080'
    command:
      - npm
      - run
      - dev-server
