name: janmarten_name

services:
  php:
    image: srcoder/development-php:php81-fpm
    user: 1000:1000
    volumes:
      - ./:/data

  nodejs:
    image: node:16-alpine
    working_dir: /home/node
    volumes:
      - ./:/home/node