name: Validate JSON data

on:
    push:
        branches: [master]
        paths:
            - data/**.json
            - .github/workflows/validate-data-schema.yml

    workflow_dispatch:

jobs:
    validate:
        runs-on: ubuntu-latest

        strategy:
          fail-fast: false
          matrix:
            include:
              - schema: data/employer.json
                data: data/employer/*.json
              - schema: data/event.json
                data: data/event/*.json
              - schema: data/skill.json
                data: data/skill/*.json

        steps:
            - uses: actions/checkout@v4

            - uses: ammarlakis/action-ajv@master
              with:
                schema: ${{ matrix.schema }}
                data: ${{ matrix.data }}
                allErrors: true
